# for i in {0..255}; do printf "\x1b[48;5;${i}m[  COLOR$(printf %03d $i)  ]\x1b[0m "; if ! ((($i+1)%8)); then echo; fi; done

set -g prefix C-a
bind C-a send-prefix
unbind C-b
unbind Space

set -g mode-keys vi
set -g display-time 3500
set -g focus-events on
set -g default-shell /bin/bash

unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind a select-window -t 10
bind b select-window -t 11

set -g pane-border-lines single 
set -g pane-border-indicators arrows

setw -g history-limit 8192 
set-window-option -g automatic-rename on
set-option -g set-titles on

set -g base-index 1
set -g pane-base-index 1

bind M-a set-option -g status-style bg=color234,fg=color15
bind M-s set-option -g status-style fg=color234,bg=color15
bind å set-option -g status-style bg=color0,fg=color15
bind ß set-option -g status-style fg=color0,bg=color15
set -g status-interval 3
set -g status-left-length 76
set -g status-right-length 151
set -g status-style fg=color234,bg=color15

set -g window-status-format         " #I:#W "
set -g window-status-current-format "#[bold,reverse] #I:#W #[default]"
set -g window-status-separator ""

set -g status-left "#[,bold] 💻 #h #[,reverse]#{?client_prefix,#[fg=red],} 🚽 #S #{?window_zoomed_flag, 📣 ,} ⚡  #[,default]#{?client_prefix,#[fg=red],#[fg=default]} "
set -g status-right "#[,bold,reverse] #D  📅 %A %B %d %Y  ⏳ %H:%M #[,default,bold]"
